### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by nextglabs** [bunred/bunadmin#20]
Hello Chris!

I just discovering `bunadmin` while searching around in Github, do you need help to improve this project?

**Comment by Chris533** [comment]
Hi **Bassem**!
Yes, my own strength is very limited, do you have any good ideas?
I need your help, and I will continue to improve this project.
I recently used `bunadmin` on the desktop such as `electron`, `tauri`.

**Comment by nextglabs** [comment]
Let me know if we could chat about this over Discord or similar

**Comment by Chris533** [comment]
I used Discord less before, just created a new server: https://discord.gg/4EjamW9zCf, see you there.
